languageCode: "en"
title: "larsgraubner.com"
baseURL: "https://larsgraubner.com"
paginate: 10
permalinks:
  post: "/:title/"
taxonomies:
  category: "categories"
Author:
  name: Lars Graubner
  email: mail@larsgraubner.de
blackfriday:
  extensionsmask: ["autolink"]

params:
  slogan: Front-end developer. Passionate about React and web performance. 🚀
