languageCode: "en"
title: "larsgraubner.com"
baseURL: "https://larsgraubner.com"
paginate: 20
permalinks:
  post: "/:title/"
taxonomies:
  category: "categories"
author:
  name: "Lars Graubner"
  email: "mail@larsgraubner.de"
blackfriday:
  extensionsmask: ["autolink"]
params:
  slogan: "Front-end developer. Passionate about React and Full Stack JavaScript. 🚀"
outputs:
  home: ["HTML"]
preserveTaxonomyNames: true
disableHugoGeneratorInject: true
metaDataFormat: "yaml"
